#genus occurance
Asiminaoccurrence<-BIEN_occurrence_genus("Asimina")
Ceanothusoccurrence<-BIEN_occurrence_genus("Ceanothus")
Circaeaoccurrence<-BIEN_occurrence_genus("Circaea")
Eubotrysoccurrence<-BIEN_occurrence_genus("Eubotrys")
Fothergillaoccurrence<-BIEN_occurrence_genus("Fothergilla")
Gaylussaciaoccurrence<-BIEN_occurrence_genus("Gaylussacia")
Hudsoniaoccurrence<-BIEN_occurrence_genus("Hudsonia")
Hypericumoccurrence<-BIEN_occurrence_genus("Hypericum")
Ilexoccurrence<-BIEN_occurrence_genus("Ilex")
Juglansoccurrence<-BIEN_occurrence_genus("Juglans")
Kalmiaoccurrence<-BIEN_occurrence_genus("Kalmia")
Paxistimaoccurrence<-BIEN_occurrence_genus("Paxistima")
Prunusoccurrence<-BIEN_occurrence_genus("Prunus")
Pteleaoccurrence<-BIEN_occurrence_genus("Ptelea")
Quercusoccurrence<-BIEN_occurrence_genus("Quercus")
Robiniaoccurrence<-BIEN_occurrence_genus("Robinia")
Sambucusoccurrence<-BIEN_occurrence_genus("Sambucus")
Sideroxylonoccurrence<-BIEN_occurrence_genus("Sideroxylon")
Ulmusoccurrence<-BIEN_occurrence_genus("Ulmus")
Vitisoccurrence<-BIEN_occurrence_genus("Vitis")




#shapefile occurance (takes too long to run)
BIEN_occurrence_shapefile(Asiminarange)
BIEN_occurrence_shapefile(Ceanothusrange)
BIEN_occurrence_shapefile(Circaearange)
BIEN_occurrence_shapefile(Eubotrysrange)
BIEN_occurrence_shapefile(Fothergillarange)
BIEN_occurrence_shapefile(Gaylussaciaarange)
BIEN_occurrence_shapefile(Hudsoniarange)
BIEN_occurrence_shapefile(Hypericumrange)
BIEN_occurrence_shapefile(Ilexrange)
BIEN_occurrence_shapefile(Juglansrange)
BIEN_occurrence_shapefile(Kalmiarange)
BIEN_occurrence_shapefile(Paxistimarange)
BIEN_occurrence_shapefile(Prunusrange)
BIEN_occurrence_shapefile(Ptelearange)
BIEN_occurrence_shapefile(Quercusrange)
BIEN_occurrence_shapefile(Robiniarange)
BIEN_occurrence_shapefile(Sambucusrange)
BIEN_occurrence_shapefile(Sideroxylonrange)
BIEN_occurrence_shapefile(Ulmusrange)
BIEN_occurrence_shapefile(Vitisrange)


AsiminaCoord=subset(Asiminaoccurrence, latitude & longitude>-180)
CeanothusCoord=subset(Ceanothusoccurrence, latitude & longitude)
CircaeaCoord=subset(Circaeaoccurrence, latitude & longitude)
EubotrysCoord=subset(Eubotrysoccurrence, latitude & longitude)
FothergillaCoord=subset(Fothergillaoccurrence, latitude & longitude)
GaylussaciaCoord=subset(Gaylussaciaoccurrence, latitude & longitude)
HudsoniaCoord=subset(Hudsoniaoccurrence, latitude & longitude)
HypericumCoord=subset(Hypericumoccurrence, latitude & longitude)
IlexCoord=subset(Ilexoccurrence, latitude & longitude)
JuglansCoord=subset(Juglansoccurrence, latitude & longitude)
KalmiaCoord=subset(Kalmiaoccurrence, latitude & longitude)
PaxistimaCoord=subset(Paxistimaoccurrence, latitude & longitude)
PrunusCoord=subset(Prunusoccurrence, latitude & longitude)
PteleaCoord=subset(Pteleaoccurrence, latitude & longitude)
QuercusCoord=subset(Quercusoccurrence, latitude &longitude)
RobiniaCoord=subset(Robiniaoccurrence, latitude & longitude)
SambucusCoord=subset(Sambucusoccurrence, latitude & longitude)
SideroxylonCoord=subset(Sideroxylonoccurrence, latitude & longitude)
UlmusCoord=subset(Ulmusoccurrence, latitude & longitude)
VitisCoord=subset(Vitisoccurrence, latitude & longitude)





